version: '3.8'

services:
  backend:
    depends_on:
      - database
    build: .
    env_file:
      - .env
    environment:
      DB_CONNECT_URI: mongodb://database/db
    ports:
      - '3000:3000'
  database:
    image: mongo:latest
    volumes:
      - db:/data/db
    ports:
      - '27018:27017'

volumes:
  db:
